version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: doselog_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: doselog_user
      POSTGRES_PASSWORD: doselog_pass
      POSTGRES_DB: doselog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb

volumes:
  postgres_data:
